import = [
	"~/.config/alacritty/themes/themes/gruvbox_dark.toml"
]

[font]
normal = { family = "FiraCode Nerd Font Mono" }

[[keyboard.bindings]]
action = "CreateNewWindow"
key = "N"
mods = "Control"
